site_name: Open-C3
site_url: https://www.open-c3.online/
site_description: OpenC3 一个开源的 自动化运维 平台 (DevOps)
site_author: lijinfeng2011@gmail.com

repo_url: https://github.com/open-c3/docs/
edit_uri: blob/main/docs/

nav:
- 首页: index.md
- 快速开始: getting-started.md
- 用户指南: user-guide/
- 演示环境: 演示环境.md
- 关于: about/

theme:
  name: mkdocs
  custom_dir: docs/overrides

markdown_extensions:
  - attr_list
